### ISSUE TITLE
sh: drush: not found

### ISSUE THREAD

**Issue by loopy3025** [docksal/qa-suite#5]
This suite works great until I try to use any of the Drupal specific steps.

Here is my behat.yml:
```
# Local overrides to the default profile
default:
  suites:
    default:
      contexts:
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - FeatureContext:
            parameters:
              screenshot_dir: %paths.base%/screenshots

  extensions:
    Behat\MinkExtension:
      goutte:
        guzzle_parameters:
          verify: false
      selenium2: ~
      # Use goutte (basic PHP browser, super fast) as the default driver.
      default_session: goutte
      # For real browser testing and tests requiring JS use selenium2 driver.
      # Tag features/scenarious with @javascript to use the selenium2 driver.
      javascript_session: selenium2
      # Configure browser to be used. Browser must be available on wd_host.
      # Stick with chrome by default. It's 2x faster than firefox or phantomjs (your results may vary).
      browser_name: chrome
      selenium2:
        wd_host: http://browser:4444/wd/hub
        capabilities: { "browser": "chrome", "version": "*" }

    Drupal\DrupalExtension:
      drush:
        alias: 'self'
      blackbox: ~
      api_driver: 'drush'
      # Map template regions.
      region_map:
        header: "#header"
        content: "#content"
        footer: "#footer"
      # Map selectors.
      selectors:
        message_selector: '#messages'
        error_message_selector: '#messages .messages.error'
        success_message_selector: '#messages .messages.status'

    # Behat HTML formatter.
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig,Behat2
      file_name: index
      print_args: true
      print_outp: true
      loop_break: true

docker:
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~

```

Here is my feature:
```
Feature: Test Boilerplate d8 Project Administrator Role
  As an administrator user
  I should be able to log in

  @api
  Scenario: Open home page and find text
    Given I am on "http://drupal8.docksal:8080"
    Given I am logged in as a user with the "administrator" role
    Then I should see text matching "My account"
```

I get the following result:
```
$ fin behat features/d8-admin.feature
Feature: Test Boilerplate d8 Project Administrator Role
  As an administrator user
  I should be able to log in

  @api
  Scenario: Open home page and find text                         # features/d8-admin.feature:6
    Given I am on "http://drupal8.docksal:8080"                  # Drupal\DrupalExtension\Context\MinkContext::visit()
    Given I am logged in as a user with the "administrator" role # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
      sh: drush: not found
       (RuntimeException)
    Then I should see text matching "My account"                 # Drupal\DrupalExtension\Context\MinkContext::assertPageMatchesText()

--- Failed scenarios:

    features/d8-admin.feature:6

1 scenario (1 failed)
3 steps (1 passed, 1 failed, 1 skipped)
0m0.19s (11.40Mb)
```
fin drush does run fine on the qa-suite container which I wouldn't expect from the error message. Is there some kind of magic with where I'm supposed to put the aliases for these sites? I'm testing against other docksal sites, so should I create aliases for those sites somewhere in this qa-suite container?  Is there a way for me to specify the alias in the feature itself? I'd like to be able to test many different sites using this one container.
