### ISSUE TITLE
[Question][backstopjs] How can we access report using a configured URL?

### ISSUE THREAD

**Issue by diegom-ciandt** [docksal/qa-suite#7]
Hi.

On my docker.yml file, i'm trying the following configuration to access backstopjs report directly:

```
services:
  backstopjs:
    image: backstopjs/backstopjs:latest
    volumes:
      - ${PROJECT_ROOT}/tests/backstopjs:/src
    labels:
      io.docksal.virtual-host: backstop.${VIRTUAL_HOST}
    entrypoint: "/bin/sh"
    stdin_open: true
    tty: true
```

However it's giving error 500 for me.
Do you have any idea what can I do?
Also, can we open a default configuration for it on this repo?
